### ISSUE TITLE
라인 수 제한과 infinite scroll in dashboard panel

### ISSUE THREAD

**Issue by YunanJeong** [YunanJeong/plg-stack#6]
# Loki 쿼리시 제한 엔트리(라인)는 기본 5000으로 설정되어있으며 얼마든지 변경가능

```yaml
# 쿼리 엔트리(라인) 수 제한. # default: 5000
# config에서 이 설정을 주석처리하면 제한없애기 가능한데, helm value 특성상 힘드므로 매우 큰 값 부여가능
loki:
  config:
    limits_config:
      max_entries_limit_per_query: 1000000  
```

# Grafana에서 최종 출력 라인 수 제한
- Datasource에서 라인제한 설정, Dashboard에서 라인제한 설정이 각각 있음
- default: 1000라인
- 출력 라인 수가 1000라인을 넘어간다면 시간대를 재설정해서 쿼리하거나, 다른 조건식을 붙여 라인 수를 줄여줘야 한다.

# 현재 Grafana에서는 infinite scroll이 안되고, 단일 쿼리만 지원한다.
- 대시보드에서 스크롤 내리면 새 쿼리가 되는게 아니라, 대시보드 새로 고침시 딱 한번 쿼리된 걸 계속 보여 주는 방식이다.

# Grafana infinite scroll: Checklist
- which version grafana?
- helm chart support? (grafana/grafana, or grafana/loki-stack)
https://github.com/grafana/grafana/issues/71728

**Comment by YunanJeong** [comment]
grafana 11.1 버전 에서 등록될 것으로 추정

https://github.com/grafana/grafana/pull/87493#issuecomment-2147528474

**Comment by YunanJeong** [comment]
- 현재, explore에서만 가능하고 dashboards는 불가
  - => 위 71728 참고. panel에서 가능하다는게 explore 모드의 패널을 의미하는 듯.


# 무한 스크롤 활성화 방법
- 해당 기능은 토글기능에 포함됨. 먼저 "토글기능 활성화" 및 "토글설정 페이지 활성화" 먼저 해줘야 함
- 이후 토글 기능 목록에서 `logsInfiniteScrolling` flag를 활성화하면 됨
- => 해당 flag는 default로 활성화된 것 같음

## [토글 활성화 방법](https://grafana.com/docs/grafana/latest/administration/feature-toggles/#manage-feature-toggles)
  - Grafana UI: Grafana Home > Administration > General > Settings 
  - 또는 Grafana Chart 
```
grafana:
  (...)
  # Grafana Home > Administration > General > Settings 제어
  grafana.ini:
    feature_toggles:
      enable: true
      featureToggleAdminPage: true
    feature_management:
      allow_editing: true
```

## [각 토글 기능에 대한 설명](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/)
